pipeline {
  agent any
  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO = "eks-automation-repo"
  }
  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/2021wa15539@wilp.bits-pilani.ac.in/driver-monitoring-app.git'
      }
    }
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $ECR_REPO:latest ./src'
      }
    }
    stage('Push to ECR') {
      steps {
        sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.$AWS_REGION.amazonaws.com'
        sh 'docker tag $ECR_REPO:latest <2021wa15539@wilp.bits-pilani.ac.in>.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest'
        sh 'docker push <2021wa15539@wilp.bits-pilani.ac.in>.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest'
      }
    }
    stage('Deploy to EKS') {
      steps {
        sh 'kubectl apply -f k8s/deployment.yaml'
      }
    }
  }
}

